package com.example.usergroup.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.usergroup.data.entity.UserEntityValues;

import com.example.usergroup.dao.UserEntityValuesDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userEntityValuesDaoConfig;

    private final UserEntityValuesDao userEntityValuesDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userEntityValuesDaoConfig = daoConfigMap.get(UserEntityValuesDao.class).clone();
        userEntityValuesDaoConfig.initIdentityScope(type);

        userEntityValuesDao = new UserEntityValuesDao(userEntityValuesDaoConfig, this);

        registerDao(UserEntityValues.class, userEntityValuesDao);
    }
    
    public void clear() {
        userEntityValuesDaoConfig.clearIdentityScope();
    }

    public UserEntityValuesDao getUserEntityValuesDao() {
        return userEntityValuesDao;
    }

}
